name: Hello universe
on: # When will it trigger
  push: # On push it will trigger
    branches: # Which branch will it trigger 
      - main # On Main branch it will trigger
  workflow_dispatch:
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Code
        uses: actions/checkout@v2 # what it does
      - name: compile Java File # Name of the steps 
        shell: bash # what shell to use
        run: javac Main.java # What it does
      - name: Run the Java File # Name of the steps
        shell: bash # What shell to use
        run: java Main # what it does
  
